version: "3"

volumes:
  berthy-db-volume:

services:
  nginx:
    image: 'nginx'
    restart: always
    volumes:
      - ./config/nginx-balancer.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/berthy.tk/fullchain.pem:/etc/ssl/certs/cert.pem
      - /etc/letsencrypt/live/berthy.tk/privkey.pem:/etc/ssl/private/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - berthy-back
      - berthy-front

  berthy-front:
    image: berthy/berthy-front:latest
    restart: always
    depends_on:
      - berthy-back

  berthy-back:
    image: berthy/berthy-back:latest
    restart: always
    volumes:
      - ./logs:/tmp/logs
      - ./files:/tmp/files
      - ./config:/tmp/config
    env_file:
      - ./config/secrets.env
    depends_on:
      - berthy-db

  berthy-db:
    image: postgres:12.4
    restart: on-failure
    volumes:
      - berthy-db-volume:/var/lib/postgresql/data
      - ./config/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./config/secrets.env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
